### ISSUE TITLE
> Shizuku خطأ في التثبيت:

### ISSUE THREAD

**Issue by apusaiiafahmad12** [apusaiiafahmad12/First-app#3]
> Shizuku خطأ في التثبيت:
> 
>  الجهاز: Redmi 22011119TI | MIUI | Android 12 | Using CopyToFileApkSource ApkSource implementation | SAI 4.5
> 
> java.lang.IllegalArgumentException: لا يحتوي ملف الـ ZIP علي أي ملفات APK
> 	at com.aefyr.sai.model.apksource.ZipApkSource.nextApk(ZipApkSource.java:58)
> 	at com.aefyr.sai.model.apksource.CopyToFileApkSource.nextApk(CopyToFileApkSource.java:33)
> 	at com.aefyr.sai.installer.ShellSAIPackageInstaller.installApkFiles(ShellSAIPackageInstaller.java:85)
> 	at com.aefyr.sai.installer.SAIPackageInstaller.lambda$processQueue$0$SAIPackageInstaller(SAIPackageInstaller.java:90)
> 	at com.aefyr.sai.installer.-$$Lambda$SAIPackageInstaller$JoIX5zHO8wAlRUBL4_c01BL_9V0.run(Unknown Source:4)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
> 	at java.lang.Thread.run(Thread.java:1012)
> 

_Originally posted by @apusaiiafahmad12 in https://github.com/apusaiiafahmad12/First-app/issues/2#issuecomment-1885376430_

**Comment by apusaiiafahmad12** [comment]
java.lang.Thread.run
